use_frameworks!

target 'ConsistencyManagerDemo' do
    pod 'ConsistencyManager', :path => '..'
end

target 'ConsistencyManagerDemoTests' do
    pod 'ConsistencyManager', :path => '..'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

